// This file is auto-generated by scripts/sync-model-ids.ts.
// Do not edit by hand.

export type ClaudeAgentSdkModelInfo = {
  modelId: string;
  displayName: string;
  description?: string;
};

export const claudeAgentSdkModelInfoById = {
  default: {
    modelId: "default",
    displayName: "Default (recommended)",
    description: "Alias to the Claude Code default model. Opus 4.6 · Most capable for complex work",
  },
  haiku: {
    modelId: "haiku",
    displayName: "Haiku",
    description: "Haiku 4.5 · Fastest for quick answers",
  },
  "opus[1m]": {
    modelId: "opus[1m]",
    displayName: "Opus (1M context)",
    description: "Opus 4.6 with 1M context · Billed as extra usage · $10/$37.50 per Mtok",
  },
  sonnet: {
    modelId: "sonnet",
    displayName: "Sonnet",
    description: "Sonnet 4.6 · Best for everyday tasks",
  },
  "sonnet[1m]": {
    modelId: "sonnet[1m]",
    displayName: "Sonnet (1M context)",
    description: "Sonnet 4.6 with 1M context · Billed as extra usage · $6/$22.50 per Mtok",
  },
} as const satisfies Record<string, ClaudeAgentSdkModelInfo>;

export function getClaudeAgentSdkModelInfo(modelId: string): ClaudeAgentSdkModelInfo | undefined {
  if (modelId in claudeAgentSdkModelInfoById) {
    return claudeAgentSdkModelInfoById[modelId as keyof typeof claudeAgentSdkModelInfoById];
  }

  let matchedModelId: string | undefined;
  for (const knownModelId of Object.keys(claudeAgentSdkModelInfoById)) {
    if (!modelId.startsWith(knownModelId)) {
      continue;
    }

    if (matchedModelId == null || knownModelId.length > matchedModelId.length) {
      matchedModelId = knownModelId;
    }
  }

  if (matchedModelId == null) {
    return undefined;
  }

  return claudeAgentSdkModelInfoById[matchedModelId as keyof typeof claudeAgentSdkModelInfoById];
}
