// This file is auto-generated by scripts/sync-model-ids.ts.
// Do not edit by hand.

export const claudeAgentSdkModelIds = [
  "default",
  "haiku",
  "opus[1m]",
  "sonnet",
  "sonnet[1m]",
] as const;

export type ClaudeAgentSdkModelId = (typeof claudeAgentSdkModelIds)[number] | (string & {});
