import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import {
  query,
  type ModelInfo,
  type Options,
  type SDKUserMessage,
} from "@anthropic-ai/claude-agent-sdk";

type ModelCatalog = {
  modelIds: string[];
  modelInfoById: Record<string, { modelId: string; displayName: string; description?: string }>;
};

async function main(): Promise<void> {
  const models = await listModels();

  if (models.length === 0) {
    throw new Error(
      [
        "No models returned by Claude Agent SDK.",
        "Verify authentication (e.g. ANTHROPIC_API_KEY / Claude CLI login) and retry.",
      ].join(" "),
    );
  }

  const catalog = buildCatalog(models);

  const modelIdsOutputPath = resolve(import.meta.dir, "../src/claude-agent-sdk-model-ids.ts");
  const modelInfoOutputPath = resolve(import.meta.dir, "../src/claude-agent-sdk-model-info.ts");

  await writeFile(modelIdsOutputPath, buildModelIdsSource(catalog.modelIds), "utf8");
  await writeFile(modelInfoOutputPath, buildModelInfoSource(catalog.modelInfoById), "utf8");

  console.log(`Updated ${modelIdsOutputPath} with ${catalog.modelIds.length} model ids`);
  console.log(`Updated ${modelInfoOutputPath} with ${catalog.modelIds.length} model info entries`);
}

async function listModels(): Promise<ModelInfo[]> {
  const run = query({
    prompt: emptyPromptStream(),
    options: buildQueryOptions(),
  });

  try {
    return await run.supportedModels();
  } finally {
    safeCloseQuery(run);
  }
}

function buildQueryOptions(): Options {
  const env: Record<string, string | undefined> = {
    ...(process.env.ANTHROPIC_API_KEY != null
      ? { ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY }
      : {}),
    ...(process.env.ANTHROPIC_AUTH_TOKEN != null
      ? { ANTHROPIC_AUTH_TOKEN: process.env.ANTHROPIC_AUTH_TOKEN }
      : {}),
    ...(process.env.ANTHROPIC_BASE_URL != null
      ? { ANTHROPIC_BASE_URL: process.env.ANTHROPIC_BASE_URL }
      : {}),
  };

  const settingSourcesRaw = process.env.CLAUDE_AGENT_SETTING_SOURCES;
  const settingSources =
    settingSourcesRaw == null || settingSourcesRaw.trim().length === 0
      ? (["project", "local"] as const)
      : parseSettingSources(settingSourcesRaw);

  return {
    cwd: process.cwd(),
    ...(settingSources.length > 0 ? { settingSources: [...settingSources] } : {}),
    ...(Object.keys(env).length > 0 ? { env } : {}),
    ...(process.env.CLAUDE_AGENT_PATH_TO_EXECUTABLE != null
      ? { pathToClaudeCodeExecutable: process.env.CLAUDE_AGENT_PATH_TO_EXECUTABLE }
      : {}),
    ...(process.env.CLAUDE_AGENT_PERMISSION_MODE != null
      ? {
          permissionMode: process.env.CLAUDE_AGENT_PERMISSION_MODE as NonNullable<
            Options["permissionMode"]
          >,
        }
      : {}),
    ...(process.env.CLAUDE_AGENT_ALLOW_DANGEROUSLY_SKIP_PERMISSIONS === "1"
      ? { allowDangerouslySkipPermissions: true }
      : {}),
  } satisfies Options;
}

function parseSettingSources(value: string): Array<"user" | "project" | "local"> {
  const out: Array<"user" | "project" | "local"> = [];

  for (const token of value.split(",")) {
    const source = token.trim();
    if (source === "user" || source === "project" || source === "local") {
      out.push(source);
      continue;
    }

    throw new Error(
      `Invalid CLAUDE_AGENT_SETTING_SOURCES value: ${source}. Expected comma-separated user,project,local.`,
    );
  }

  return out;
}

function buildCatalog(models: ModelInfo[]): ModelCatalog {
  const ids = [
    ...new Set(models.map((model) => model.value).filter((value) => value.length > 0)),
  ].sort((a, b) => a.localeCompare(b));

  const infoById: Record<string, { modelId: string; displayName: string; description?: string }> =
    {};
  for (const id of ids) {
    const model = models.find((entry) => entry.value === id);
    const description = normalizeDescription(id, model?.description);

    infoById[id] = {
      modelId: id,
      displayName: model?.displayName ?? id,
      ...(description != null ? { description } : {}),
    };
  }

  return {
    modelIds: ids,
    modelInfoById: infoById,
  };
}

function normalizeDescription(
  modelId: string,
  description: string | undefined,
): string | undefined {
  if (description == null || description.length === 0) {
    return undefined;
  }

  if (modelId === "default") {
    return `Alias to the Claude Code default model. ${description}`;
  }

  return description;
}

function buildModelIdsSource(modelIds: string[]): string {
  return [
    "// This file is auto-generated by scripts/sync-model-ids.ts.",
    "// Do not edit by hand.",
    "",
    "export const claudeAgentSdkModelIds = [",
    ...modelIds.map((modelId) => `  ${JSON.stringify(modelId)},`),
    "] as const;",
    "",
    "export type ClaudeAgentSdkModelId = (typeof claudeAgentSdkModelIds)[number] | (string & {});",
    "",
  ].join("\n");
}

function buildModelInfoSource(
  modelInfoById: Record<string, { modelId: string; displayName: string; description?: string }>,
): string {
  const modelIds = Object.keys(modelInfoById).sort((a, b) => a.localeCompare(b));

  return [
    "// This file is auto-generated by scripts/sync-model-ids.ts.",
    "// Do not edit by hand.",
    "",
    "export type ClaudeAgentSdkModelInfo = {",
    "  modelId: string;",
    "  displayName: string;",
    "  description?: string;",
    "};",
    "",
    "export const claudeAgentSdkModelInfoById = {",
    ...modelIds.map((modelId) => {
      const model = modelInfoById[modelId];
      const fields = [
        `modelId: ${JSON.stringify(model.modelId)}`,
        `displayName: ${JSON.stringify(model.displayName)}`,
        ...(model.description != null ? [`description: ${JSON.stringify(model.description)}`] : []),
      ];

      return `  ${JSON.stringify(modelId)}: { ${fields.join(", ")} },`;
    }),
    "} as const satisfies Record<string, ClaudeAgentSdkModelInfo>;",
    "",
    "export function getClaudeAgentSdkModelInfo(modelId: string): ClaudeAgentSdkModelInfo | undefined {",
    "  if (modelId in claudeAgentSdkModelInfoById) {",
    "    return claudeAgentSdkModelInfoById[modelId as keyof typeof claudeAgentSdkModelInfoById];",
    "  }",
    "",
    "  let matchedModelId: string | undefined;",
    "  for (const knownModelId of Object.keys(claudeAgentSdkModelInfoById)) {",
    "    if (!modelId.startsWith(knownModelId)) {",
    "      continue;",
    "    }",
    "",
    "    if (matchedModelId == null || knownModelId.length > matchedModelId.length) {",
    "      matchedModelId = knownModelId;",
    "    }",
    "  }",
    "",
    "  if (matchedModelId == null) {",
    "    return undefined;",
    "  }",
    "",
    "  return claudeAgentSdkModelInfoById[matchedModelId as keyof typeof claudeAgentSdkModelInfoById];",
    "}",
    "",
  ].join("\n");
}

async function* emptyPromptStream(): AsyncGenerator<SDKUserMessage, void, void> {}

function safeCloseQuery(run: ReturnType<typeof query>): void {
  try {
    run.close();
  } catch {
    // ignore close errors during cleanup
  }
}

await main();
