import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const SUPPORTED_REASONING_EFFORTS = ["minimal", "low", "medium", "high", "xhigh"] as const;
const SUPPORTED_INPUT_MODALITIES = ["text", "image"] as const;

type CodexModelsPayload = {
  models?: Array<{
    slug?: string;
    display_name?: string;
    description?: string | null;
    context_window?: number | null;
    input_modalities?: string[];
    supported_reasoning_levels?: Array<{ effort?: string }>;
    default_reasoning_level?: string | null;
    supports_parallel_tool_calls?: boolean;
    supported_in_api?: boolean;
  }>;
};

const DEFAULT_MODELS_URL =
  "https://raw.githubusercontent.com/openai/codex/main/codex-rs/core/models.json";

async function main(): Promise<void> {
  const modelsUrl = process.env.CODEX_MODELS_JSON_URL ?? DEFAULT_MODELS_URL;

  const response = await fetch(modelsUrl);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${modelsUrl}: ${response.status} ${response.statusText}`);
  }

  const payload = (await response.json()) as CodexModelsPayload;
  const rawModels = (payload.models ?? []).filter((model) => isString(model.slug));

  const modelIds = [...new Set(rawModels.map((model) => model.slug!))].sort((a, b) =>
    a.localeCompare(b),
  );

  if (modelIds.length === 0) {
    throw new Error(`No model slugs found in payload from ${modelsUrl}`);
  }

  const modelIdsOutput = [
    "// This file is auto-generated by scripts/sync-model-ids.ts.",
    "// Do not edit by hand.",
    "",
    "export const codexSdkModelIds = [",
    ...modelIds.map((modelId) => `  ${JSON.stringify(modelId)},`),
    "] as const;",
    "",
    "export type CodexSdkModelId = (typeof codexSdkModelIds)[number] | (string & {});",
    "",
  ].join("\n");

  const modelInfoOutput = [
    "// This file is auto-generated by scripts/sync-model-ids.ts.",
    "// Do not edit by hand.",
    "",
    `export type CodexSdkReasoningEffort = ${SUPPORTED_REASONING_EFFORTS.map((value) => JSON.stringify(value)).join(" | ")};`,
    `export type CodexSdkInputModality = ${SUPPORTED_INPUT_MODALITIES.map((value) => JSON.stringify(value)).join(" | ")};`,
    "",
    "export type CodexSdkModelInfo = {",
    "  modelId: string;",
    "  displayName: string;",
    "  description?: string;",
    "  contextWindow?: number;",
    "  inputModalities: readonly CodexSdkInputModality[];",
    "  supportedReasoningEfforts: readonly CodexSdkReasoningEffort[];",
    "  defaultReasoningEffort?: CodexSdkReasoningEffort;",
    "  supportsParallelToolCalls: boolean;",
    "  supportedInApi: boolean;",
    "};",
    "",
    "export const codexSdkModelInfoById = {",
    ...modelIds.map((modelId) => {
      const model = rawModels.find((entry) => entry.slug === modelId)!;
      const supportedReasoningEfforts = [
        ...new Set(
          (model.supported_reasoning_levels ?? [])
            .map((level) => level.effort)
            .filter(isReasoningEffort),
        ),
      ];
      const inputModalities = [...new Set((model.input_modalities ?? []).filter(isInputModality))];
      const description = isString(model.description) ? model.description : undefined;
      const contextWindow =
        typeof model.context_window === "number" ? model.context_window : undefined;
      const defaultReasoningEffort = isReasoningEffort(model.default_reasoning_level)
        ? model.default_reasoning_level
        : undefined;
      const displayName = isString(model.display_name) ? model.display_name : modelId;
      const supportsParallelToolCalls = model.supports_parallel_tool_calls === true;
      const supportedInApi = model.supported_in_api !== false;

      const fields = [
        `modelId: ${JSON.stringify(modelId)}`,
        `displayName: ${JSON.stringify(displayName)}`,
        ...(description != null ? [`description: ${JSON.stringify(description)}`] : []),
        ...(contextWindow != null ? [`contextWindow: ${contextWindow}`] : []),
        `inputModalities: [${(inputModalities.length > 0 ? inputModalities : ["text"])
          .map((value) => JSON.stringify(value))
          .join(", ")}]`,
        `supportedReasoningEfforts: [${supportedReasoningEfforts
          .map((value) => JSON.stringify(value))
          .join(", ")}]`,
        ...(defaultReasoningEffort != null
          ? [`defaultReasoningEffort: ${JSON.stringify(defaultReasoningEffort)}`]
          : []),
        `supportsParallelToolCalls: ${JSON.stringify(supportsParallelToolCalls)}`,
        `supportedInApi: ${JSON.stringify(supportedInApi)}`,
      ];

      return [
        `  ${JSON.stringify(modelId)}: {`,
        ...fields.map((field) => `    ${field},`),
        "  },",
      ].join("\n");
    }),
    "} as const satisfies Record<string, CodexSdkModelInfo>;",
    "",
    "export function getCodexSdkModelInfo(modelId: string): CodexSdkModelInfo | undefined {",
    "  if (modelId in codexSdkModelInfoById) {",
    "    return codexSdkModelInfoById[modelId as keyof typeof codexSdkModelInfoById];",
    "  }",
    "",
    "  let matchedModelId: string | undefined;",
    "  for (const knownModelId of Object.keys(codexSdkModelInfoById)) {",
    "    if (!modelId.startsWith(knownModelId)) {",
    "      continue;",
    "    }",
    "    if (matchedModelId == null || knownModelId.length > matchedModelId.length) {",
    "      matchedModelId = knownModelId;",
    "    }",
    "  }",
    "",
    "  if (matchedModelId == null) {",
    "    return undefined;",
    "  }",
    "",
    "  return codexSdkModelInfoById[matchedModelId as keyof typeof codexSdkModelInfoById];",
    "}",
    "",
  ].join("\n");

  const modelIdsOutputPath = resolve(import.meta.dir, "../src/codex-sdk-model-ids.ts");
  await writeFile(modelIdsOutputPath, modelIdsOutput, "utf8");

  const modelInfoOutputPath = resolve(import.meta.dir, "../src/codex-sdk-model-info.ts");
  await writeFile(modelInfoOutputPath, modelInfoOutput, "utf8");

  console.log(`Updated ${modelIdsOutputPath} with ${modelIds.length} model ids from ${modelsUrl}`);
  console.log(`Updated ${modelInfoOutputPath} with ${modelIds.length} model info entries`);
}

function isString(value: unknown): value is string {
  return typeof value === "string" && value.length > 0;
}

function isReasoningEffort(value: unknown): value is (typeof SUPPORTED_REASONING_EFFORTS)[number] {
  return (
    typeof value === "string" && (SUPPORTED_REASONING_EFFORTS as readonly string[]).includes(value)
  );
}

function isInputModality(value: unknown): value is (typeof SUPPORTED_INPUT_MODALITIES)[number] {
  return (
    typeof value === "string" && (SUPPORTED_INPUT_MODALITIES as readonly string[]).includes(value)
  );
}

await main();
