// This file is auto-generated by scripts/sync-model-ids.ts.
// Do not edit by hand.

export const codexSdkModelIds = [
  "gpt-5",
  "gpt-5-codex",
  "gpt-5-codex-mini",
  "gpt-5.1",
  "gpt-5.1-codex",
  "gpt-5.1-codex-max",
  "gpt-5.1-codex-mini",
  "gpt-5.2",
  "gpt-5.2-codex",
  "gpt-5.3-codex",
] as const;

export type CodexSdkModelId = (typeof codexSdkModelIds)[number] | (string & {});
