// This file is auto-generated by scripts/sync-model-ids.ts.
// Do not edit by hand.

export type CodexSdkReasoningEffort = "minimal" | "low" | "medium" | "high" | "xhigh";
export type CodexSdkInputModality = "text" | "image";

export type CodexSdkModelInfo = {
  modelId: string;
  displayName: string;
  description?: string;
  contextWindow?: number;
  inputModalities: readonly CodexSdkInputModality[];
  supportedReasoningEfforts: readonly CodexSdkReasoningEffort[];
  defaultReasoningEffort?: CodexSdkReasoningEffort;
  supportsParallelToolCalls: boolean;
  supportedInApi: boolean;
};

export const codexSdkModelInfoById = {
  "gpt-5": {
    modelId: "gpt-5",
    displayName: "gpt-5",
    description: "Broad world knowledge with strong general reasoning.",
    contextWindow: 272000,
    inputModalities: ["text", "image"],
    supportedReasoningEfforts: ["minimal", "low", "medium", "high"],
    defaultReasoningEffort: "medium",
    supportsParallelToolCalls: false,
    supportedInApi: true,
  },
  "gpt-5-codex": {
    modelId: "gpt-5-codex",
    displayName: "gpt-5-codex",
    description: "Optimized for codex.",
    contextWindow: 272000,
    inputModalities: ["text", "image"],
    supportedReasoningEfforts: ["low", "medium", "high"],
    defaultReasoningEffort: "medium",
    supportsParallelToolCalls: false,
    supportedInApi: true,
  },
  "gpt-5-codex-mini": {
    modelId: "gpt-5-codex-mini",
    displayName: "gpt-5-codex-mini",
    description: "Optimized for codex. Cheaper, faster, but less capable.",
    contextWindow: 272000,
    inputModalities: ["text", "image"],
    supportedReasoningEfforts: ["medium", "high"],
    defaultReasoningEffort: "medium",
    supportsParallelToolCalls: false,
    supportedInApi: true,
  },
  "gpt-5.1": {
    modelId: "gpt-5.1",
    displayName: "gpt-5.1",
    description: "Broad world knowledge with strong general reasoning.",
    contextWindow: 272000,
    inputModalities: ["text", "image"],
    supportedReasoningEfforts: ["low", "medium", "high"],
    defaultReasoningEffort: "medium",
    supportsParallelToolCalls: true,
    supportedInApi: true,
  },
  "gpt-5.1-codex": {
    modelId: "gpt-5.1-codex",
    displayName: "gpt-5.1-codex",
    description: "Optimized for codex.",
    contextWindow: 272000,
    inputModalities: ["text", "image"],
    supportedReasoningEfforts: ["low", "medium", "high"],
    defaultReasoningEffort: "medium",
    supportsParallelToolCalls: false,
    supportedInApi: true,
  },
  "gpt-5.1-codex-max": {
    modelId: "gpt-5.1-codex-max",
    displayName: "gpt-5.1-codex-max",
    description: "Codex-optimized flagship for deep and fast reasoning.",
    contextWindow: 272000,
    inputModalities: ["text", "image"],
    supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
    defaultReasoningEffort: "medium",
    supportsParallelToolCalls: false,
    supportedInApi: true,
  },
  "gpt-5.1-codex-mini": {
    modelId: "gpt-5.1-codex-mini",
    displayName: "gpt-5.1-codex-mini",
    description: "Optimized for codex. Cheaper, faster, but less capable.",
    contextWindow: 272000,
    inputModalities: ["text", "image"],
    supportedReasoningEfforts: ["medium", "high"],
    defaultReasoningEffort: "medium",
    supportsParallelToolCalls: false,
    supportedInApi: true,
  },
  "gpt-5.2": {
    modelId: "gpt-5.2",
    displayName: "gpt-5.2",
    description: "Latest frontier model with improvements across knowledge, reasoning and coding",
    contextWindow: 272000,
    inputModalities: ["text", "image"],
    supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
    defaultReasoningEffort: "medium",
    supportsParallelToolCalls: true,
    supportedInApi: true,
  },
  "gpt-5.2-codex": {
    modelId: "gpt-5.2-codex",
    displayName: "gpt-5.2-codex",
    description: "Frontier agentic coding model.",
    contextWindow: 272000,
    inputModalities: ["text", "image"],
    supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
    defaultReasoningEffort: "medium",
    supportsParallelToolCalls: true,
    supportedInApi: true,
  },
  "gpt-5.3-codex": {
    modelId: "gpt-5.3-codex",
    displayName: "gpt-5.3-codex",
    description: "Latest frontier agentic coding model.",
    contextWindow: 272000,
    inputModalities: ["text", "image"],
    supportedReasoningEfforts: ["low", "medium", "high", "xhigh"],
    defaultReasoningEffort: "medium",
    supportsParallelToolCalls: true,
    supportedInApi: true,
  },
} as const satisfies Record<string, CodexSdkModelInfo>;

export function getCodexSdkModelInfo(modelId: string): CodexSdkModelInfo | undefined {
  if (modelId in codexSdkModelInfoById) {
    return codexSdkModelInfoById[modelId as keyof typeof codexSdkModelInfoById];
  }

  let matchedModelId: string | undefined;
  for (const knownModelId of Object.keys(codexSdkModelInfoById)) {
    if (!modelId.startsWith(knownModelId)) {
      continue;
    }
    if (matchedModelId == null || knownModelId.length > matchedModelId.length) {
      matchedModelId = knownModelId;
    }
  }

  if (matchedModelId == null) {
    return undefined;
  }

  return codexSdkModelInfoById[matchedModelId as keyof typeof codexSdkModelInfoById];
}
